version: "3.7"

x-logging: &logging
  logging:
    driver: "local"

services:
  eth2_validator:
    user: "1001:1001"
    hostname: eth2_validator
    container_name: eth2_validator
    image: consensys/teku:develop #latest
    restart: always
    command: |
      validator-client
      --config-file "/config/config.yml"
    networks:
      net:
        ipv4_address: 192.168.32.104
    ports:
      - 9002:9002 # p2p
#      - 5051:5051 # metrics
#      - 5053:5053 # rest api
    volumes:
      - /home/eth/eth/validator/config:/config
      - /home/eth/eth/validator/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - JAVA_OPTS=-Xmx4g
    <<: *logging

networks:
  net:
    external: true
