data-path="/data"
data-storage-format="BONSAI"
nat-method="DOCKER"
sync-mode="X_CHECKPOINT"

network="goerli"

logging="INFO"
Xplugin-rocksdb-high-spec-enabled=true

max-peers=25
fast-sync-min-peers=3

host-allowlist=["*",]

p2p-enabled=true
p2p-host="0.0.0.0"
p2p-port="30304"

rpc-http-enabled=true
rpc-http-api=["WEB3", "ETH", "NET"]
rpc-http-host="0.0.0.0"
rpc-http-port="8545"
rpc-http-cors-origins=["*",]
rpc-http-max-active-connections=65536
rpc-max-logs-range=65536

rpc-ws-enabled=true
rpc-ws-api=["WEB3", "ETH", "NET"]
rpc-ws-host="0.0.0.0"
rpc-ws-port="8546"

metrics-enabled=true
metrics-host="0.0.0.0"
metrics-port="9545"

engine-host-allowlist=["*",]
engine-jwt-secret="/config/jwtsecret.hex"
engine-rpc-port="8551"
